server:
  servlet:
    context-path: /api

spring:
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  application:
    name: task

  web:
    resources:
      add-mappings: false

  jpa:
    properties:
      hibernate:
        format_sql: true
        jdbc:
          time_zone: UTC

  jackson:
    time-zone: UTC
    serialization:
      write-dates-as-timestamps: false

security:
  jwt:
    issuer: ktb4-jade-api
    audience: ktb4-jade-api

  cookie:
    access-name: access_token
    refresh-name: refresh_token
